### ISSUE TITLE
[Question] Color selection mode

### ISSUE THREAD

**Issue by DevEddy** [daltonks/Spillman.Xamarin.Forms.ColorPicker#2]
I love your control and coding style. It works really well for color picking.

I would like to use it to control a hue bulbs.
Is there a way to archive something like this (original hue app)?

![image](https://user-images.githubusercontent.com/7648336/92374535-25852c00-f100-11ea-92fe-8864f27e567d.png)

Thanks!

-- Eddy

**Comment by WorldOfBasti** [comment]
I think something like this isn't possible with that plugin. You'll need to make your own color picker. Maybe [this tutorial](https://theconfuzedsourcecode.wordpress.com/2020/02/26/i-built-an-interactive-color-picker-control-for-xamarin-forms/) will help you.

**Comment by daltonks** [comment]
Hey @DevEddy 
Sorry, I missed the initial notification on this one 💀
Yes, you should be able to use SkiaSharp to do this using the source code as an example to draw to the canvas and handle touch input. Maybe you could draw two types of gradients on top of each other? One for the colors, then one for the fading white circle on top.
I don't personally have plans to add a color picker that looks like this, but I might be able to help out with yours if you have specific SkiaSharp questions.

**Comment by daltonks** [comment]
Going to close this issue, but my offer still stands if you have any SkiaSharp issues 👍
