### ISSUE TITLE
Accepting contributions?

### ISSUE THREAD

**Issue by jamesmontemagno** [daltonks/Spillman.Xamarin.Forms.ColorPicker#3]
I would love to work on this library to update it to the latest SkiaSharp and also prep it for .NET MAUI. Thoughts on if you are open to contributions and streamlining devops pipelines?

**Comment by daltonks** [comment]
@jamesmontemagno Sure! I'll be moving to MAUI in the future anyhow, so that would be helpful!

**Comment by jamesmontemagno** [comment]
Lovely, I think overall doing 1 more release with the latest SkiaSharp + Xamarin.Forms would be nice and then transition to .NET MAUI (maybe even a new NuGet). I have a fork of this somewhere and I'll do a PR to see what I have changed :)

**Comment by daltonks** [comment]
I am publishing version 1.0.7, which is updated to the latest SkiaSharp and Xamarin.Forms dependencies. Looks good in the example app 😃

**Comment by jamesmontemagno** [comment]
Awesome!!! <3
