### ISSUE TITLE
[feature request] Hide textbox

### ISSUE THREAD

**Issue by Blackfishbox** [daltonks/Spillman.Xamarin.Forms.ColorPicker#4]
Hi,

it would be nice to hide the Textbox, as I only need to select a color but the user does not need to know the text value (hex string).
Could you make a xaml-setable property like _IsHexVisible_ or something like this?

Thank you very much in advance.

**Comment by daltonks** [comment]
Hello!
For consistency, I added the property `ColorPickerViewModel.IsHexEnabled`. The NuGet package (1.0.8) should be available soon 😎

**Comment by daltonks** [comment]
https://github.com/daltonks/Spillman.Xamarin.Forms.ColorPicker/commit/645b7eae929f44259ce840e5d48376b9fa3397be

**Comment by Blackfishbox** [comment]
Awesome thank you very much for the quick response and solution :)
